version: '3'
services:
  admin:
    image: node:8-alpine
    command: npm run start
    working_dir: /app
    volumes:
      - ./admin:/app
    ports:
      - "3000:3000"
  api:
    image: node:8-alpine
    command: npm run dev
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "8080:8080"